---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: noted
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: noted
  template:
    metadata:
      labels:
        app: noted
    spec:
      containers:
        - name: noted
          # TODO: config 1/7
          image: gerhard/noted:2021-06-18T10.42.36Z
          env:
            - name: URL_HOST
              # TODO: config 2/7
              value: "noted.k3s.gerhard.io"
            - name: URL_PORT
              value: "80"
            - name: DATABASE_URL
              value: "ecto://./database.db"
            - name: TELEGRAM_BOT_NAME
              # TODO: config 3/7
              value: "GerhardNoted"
            - name: TELEGRAM_BOT_SECRET
              valueFrom:
                secretKeyRef:
                  name: telegram-bot-secret
                  key: value
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: secret-key-base
                  key: value
          ports:
            - name: phoenix
              containerPort: 4000
          resources:
            requests:
              cpu: 0.1
              memory: 128Mi
            limits:
              cpu: 1
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /
              port: phoenix
              httpHeaders:
                - name: Host
                  value: 127.0.0.1
            periodSeconds: 10
            timeoutSeconds: 9
          startupProbe:
            httpGet:
              path: /
              port: phoenix
              httpHeaders:
                - name: Host
                  value: 127.0.0.1
            failureThreshold: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: noted
spec:
  ports:
    - name: http
      port: 4000
      protocol: TCP
      targetPort: phoenix
  selector:
    app: noted
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: noted
spec:
  entryPoints:
    - web
    - websecure
  routes:
    # TODO: config 4/7
    - match: Host(`noted.k3s.gerhard.io`)
      kind: Rule
      services:
        - name: noted
          port: 4000
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  # TODO: config 5/7
  name: noted.k3s.gerhard.io
spec:
  endpoints:
    # TODO: config 6/7
    - dnsName: noted.k3s.gerhard.io
      recordType: A
      targets:
        # TODO: config 7/7
        - 139.162.200.52
